### ISSUE TITLE
Still able to deploy 4 troops/turn when only controlling one province

### ISSUE THREAD

**Issue by clumsycapy** [TheZipCreator/qonquest2#1]
**Describe the bug**
When starting in Qonquest 2, I can of course only deploy 2 troops/turn. Sometimes, however, I will take a province with my troops only for another country to attack my home province with their troops and successfully take it. This leaves me in a sort of “migrated” position where I hold the province I just took but lost my home province. Since I had a net province gain of 0, my troop deployment count should stay at 2/turn. However, I can deploy 4 instead, as if I still held my home province.
**To Reproduce**
1. Pick a country in Qonquest 2 (I experienced this error playing as England and Ireland)
2. Invade another country using your entire army (this way your odds of winning are better whilst also increasing your odds of losing your home province)
3. Lose your home province and seize the province you invaded (if this does not occur, repeat steps 1 and 2 until it happens)
4. You should now be able to produce 4 troops/turn despite holding 1 province only. 

**Expected behavior**

I expect to only be able to produce 2 troops per turn.

**Screenshots**

I’m on mobile sorry :(

**OS**
What Operating System you're using
Windows 10, using the windows 7zip download and launching the game through the qonquest.exe file

**Additional context**
I can’t say for sure but I don’t remember if the bug happens 100% of the time, I think there have been instances where I go from 2 provinces to 1 and I can only deploy 2 troops/turn. I haven’t tested this enough to determine what specific conditions need to be met for the bug to occur, so probably investigating that is your best bet at finding the source of the issue.

**Comment by zipsegv** [comment]
fixed in commit [551030392665cbbfd4d767400afea9e1541ba856](https://github.com/TheZipCreator/qonquest2/commit/551030392665cbbfd4d767400afea9e1541ba856)
