### ISSUE TITLE
I ported your game to my language, Neat!

### ISSUE THREAD

**Issue by FeepingCreature** [TheZipCreator/qonquest2#2]
Not really a bug, I just wanted to let you know. :) 

[Neat](https://neat-lang.github.io/) is a fairly close copy of D ca. 2010, so it was relatively straightforward. I found lots of compiler bugs!

https://github.com/FeepingCreature/qonquest2

Biggest problems were that Neat doesn't have global variables or circular imports. That's why there's `source/qonquest2/base.nt` now. The code could also probably be cleaned up a bunch. But honestly, I mostly did it to see if I could.

Qonquest2 was pretty great for this because it's all fairly straightforward code, and there's not very much of it. There's a lot of game in there for the lines!

Anyway. 🎉!

**Comment by zipsegv** [comment]
that's pretty cool! the language itself looks kind of interesting, I'll have to check it out.
